import{S as g,i as c}from"./assets/vendor-46aac873.js";(function(){const l=document.createElement("link").relList;if(l&&l.supports&&l.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const o of r.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&t(o)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function t(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const p=document.querySelector(".form"),u=document.createDocumentFragment(),d=document.querySelector(".gallery"),i=document.querySelector(".loader"),y="https://pixabay.com/api/",h="42159131-e2480a23f0f5c24b1f6f03d93",L={overlayOpacity:.8,captionsData:"alt",captionDelay:250},v=new g(".gallery a",L);p.addEventListener("submit",s=>{s.preventDefault(),d.innerHTML="";const l=document.querySelector("input"),a=l.value.trim();a?(m(),b(a)):c.warning({message:"You forgot to enter your details"}),l.value=""});function b(s){const a=(()=>{const t=new URL(y);return t.searchParams.append("key",h),t.searchParams.append("image_type","photo"),t.searchParams.append("orientation","horizontal"),t.searchParams.append("safesearch",!0),t})();a.searchParams.append("q",s),fetch(a).then(t=>t.json()).then(t=>{const e=t.hits;e.length>0?w(e):c.warning({message:"Sorry, there are no images matching your search query. Please try again!",color:"#f83d04"})}).catch(()=>{c.warning({message:"Request failure",color:"#f83d04"})})}function w(s){s.forEach(({webformatURL:l,largeImageURL:a,tags:t,likes:e,views:r,comments:o,downloads:f})=>{const n=document.createElement("li");n.classList.add("gallery-items"),n.insertAdjacentHTML("beforeend",`<a class='gallery-link' href='${a}'>
          <img class='gallery-image' src='${l}' alt='${t}' />
          <ul class='gallery-ul'>
          <li class='gallery-item'><h3 class='gallery-title'>Likes</h3><p class='gallery-value'>${e}</p></li>
          <li class='gallery-item'><h3 class='gallery-title'>Views</h3><p class='gallery-value'>${r}</p></li>
          <li class='gallery-item'><h3 class='gallery-title'>Comments</h3><p class='gallery-value'>${o}</p></li>
          <li class='gallery-item'><h3 class='gallery-title'>Downloads</h3><p class='gallery-value'>${f}</p></li>
        </ul>  
        </a>`),u.appendChild(n)}),m(),d.appendChild(u),v.refresh()}function m(){i.classList.contains("hide")?i.classList.remove("hide"):i.classList.add("hide")}
//# sourceMappingURL=commonHelpers.js.map
