import{S as g,i as c}from"./assets/vendor-46aac873.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const l of e)if(l.type==="childList")for(const o of l.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&t(o)}).observe(document,{childList:!0,subtree:!0});function a(e){const l={};return e.integrity&&(l.integrity=e.integrity),e.referrerpolicy&&(l.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?l.credentials="include":e.crossorigin==="anonymous"?l.credentials="omit":l.credentials="same-origin",l}function t(e){if(e.ep)return;e.ep=!0;const l=a(e);fetch(e.href,l)}})();const p=document.querySelector(".form"),i=document.createDocumentFragment(),u=document.querySelector(".gallery"),d=document.querySelector(".loader"),y="https://pixabay.com/api/",f="42159131-e2480a23f0f5c24b1f6f03d93",h={overlayOpacity:.8,captionsData:"alt",captionDelay:250},L=new g(".gallery a",h);p.addEventListener("submit",s=>{s.preventDefault(),u.innerHTML="";const r=document.querySelector("input"),a=r.value.trim();a?(d.classList.remove("hide"),v(a)):c.warning({message:"You forgot to enter your details"}),r.value=""});function v(s){const a=(()=>{const t=new URL(y);return t.searchParams.append("key",f),t.searchParams.append("image_type","photo"),t.searchParams.append("orientation","horizontal"),t.searchParams.append("safesearch",!0),t})();a.searchParams.append("q",s),fetch(a).then(t=>t.json()).then(t=>{const e=t.hits;e.length>0?b(e):c.warning({message:"Sorry, there are no images matching your search query. Please try again!",color:"#f83d04"})}).catch(t=>{console.log(t)})}function b(s){s.forEach(({webformatURL:r,largeImageURL:a,tags:t,likes:e,views:l,comments:o,downloads:m})=>{const n=document.createElement("li");n.classList.add("gallery-items"),n.insertAdjacentHTML("beforeend",`<a class="gallery-link" href="${a}">
          <img class="gallery-image" src="${r}" alt="${t}" />
          <ul class="gallery-ul">
          <li class="gallery-item"><h3 class="gallery-title">Likes</h3><p class="gallery-value">${e}</p></li>
          <li class="gallery-item"><h3 class="gallery-title">Views</h3><p class="gallery-value">${l}</p></li>
          <li class="gallery-item"><h3 class="gallery-title">Comments</h3><p class="gallery-value">${o}</p></li>
          <li class="gallery-item"><h3 class="gallery-title">Downloads</h3><p class="gallery-value">${m}</p></li>
        </ul>  
        </a>`),i.appendChild(n)}),d.classList.add("hide"),u.appendChild(i),L.refresh()}
//# sourceMappingURL=commonHelpers.js.map
